apiVersion: v1
kind: Service
metadata:
  name: example-service
spec:
  selector:
    app: example
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 32321
  type: NodePort
